name: CDK Diff

on:
  push:
    branches:
      - main
    paths:
      - "devops/**"
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read # Required to checkout the repository
  actions: write # Required to trigger workflows

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: CDK Diff
        env:
          GITHUB_ORG_NAME: ${{ github.repository_owner }}
        run: npx cdk diff

      - name: Trigger Deploy Workflow
        run: |
          gh auth login --with-token <<< "${{ github.token }}"
          gh workflow run deploy.yml --ref ${{ github.ref }}
